/**
 * EDS Block: ProductListing
 * Generated by AEM Migration Agent
 * Behavior IR: ProductListing
 * Framework: react
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  setDefaultCurrency,
  renderProductListing,
} from '../shared/generated-jsx.js';

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'ProductListing';
  if (block.dataset.currency == null) block.dataset.currency = '₹';
  setDefaultCurrency(block.dataset.currency || null);

  let data = null;
  let loading = true;
  let error = null;
  let retry = () => {};

  const renderBlock = () => {
    block.replaceChildren();
    try {
      renderProductListing(block, {
        data, loading, error, retry, currency: block.dataset.currency || null,
      });
    } catch (err) {
      const p = document.createElement('p');
      p.textContent = `Render error: ${err instanceof Error ? err.message : String(err)}`;
      block.appendChild(p);
      console.error(err); // eslint-disable-line no-console
    }
  };

  const load = async () => {
    loading = true;
    error = null;
    renderBlock();
    try {
      const response = await fetch('https://fakestoreapi.com/products');
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      data = await response.json();
      data = Array.isArray(data) ? { products: data } : data;
      (data.products || []).forEach((p) => { p.stock = p.stock ?? 10; });
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
      renderBlock();
    }
  };

  retry = load;
  await load();
}
