/**
 * EDS Block: home
 * Generated by AEM Migration Agent
 * Behavior IR: +page
 * Framework: svelte
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  setDefaultCurrency,
  renderHome,
} from '../shared/generated-jsx.js';
/* eslint-disable no-console */

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'home';
  setDefaultCurrency(block.dataset.currency || null);

  const entityKey = block.dataset.entityKey || 'id';
  let data = null;
  let loading = true;
  let error = null;
  let retry = () => {};
  let editingId = null;
  let editForm = {};
  let createForm = {};

  const renderBlock = () => {
    block.replaceChildren();
    try {
      renderHome(block, {
        data,
        loading,
        error,
        retry,
        currency: block.dataset.currency || null,
        form: createForm,
        editingId,
        editForm,
      });
    } catch (err) {
      const p = document.createElement('p');
      p.textContent = `Render error: ${err instanceof Error ? err.message : String(err)}`;
      block.appendChild(p);
      console.error(err);
    }
  };

  const load = async () => {
    loading = true;
    error = null;
    renderBlock();
    try {
      const response = await fetch(block.dataset.dataSource || 'https://dummyjson.com/products');
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      data = await response.json();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
      renderBlock();
    }
  };

  // Orchestrator state machine: consumes the component's dispatched events and
  // replays the source script handlers (real API mutations when the component
  // used an API service, otherwise local model updates).
  const onComponentEvent = async (ev) => {
    const source = ev.detail?.event?.target;
    if (source && !block.contains(source)) return;
    const { name, args = [] } = ev.detail || {};
    if (name === 'startEdit') {
      const entity = args[0];
      if (!entity) return;
      editingId = entity[entityKey];
      editForm = { ...entity };
      renderBlock();
    } else if (name === 'saveEdit' && Array.isArray(data)) {
      const id = args[0];
      data = data.map((u) => (u[entityKey] === id ? { ...u, ...editForm } : u));
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'cancelEdit') {
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'handleDelete' && Array.isArray(data)) {
      const id = args[0];
      data = data.filter((u) => u[entityKey] !== id);
      if (editingId === id) { editingId = null; editForm = {}; }
      renderBlock();
    } else if (name === 'updateField') {
      const [field, value] = args;
      if (editingId != null) editForm = { ...editForm, [field]: value || '' };
      else createForm = { ...createForm, [field]: value || '' };
    } else if (name === 'handleSubmit') {
      if (Object.keys(createForm).length === 0) return;
      data = [{ [entityKey]: Date.now(), ...createForm }, ...(Array.isArray(data) ? data : [])];
      createForm = {};
      renderBlock();
    }
  };
  document.addEventListener('eds:component-event', onComponentEvent);

  retry = load;
  await load();
}
