/**
 * EDS Block: Stars
 * Generated by AEM Migration Agent
 * Behavior IR: Stars
 * Framework: svelte
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  setDefaultCurrency,
  renderStars,
} from '../shared/generated-jsx.js';
/* eslint-disable no-console */

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'Stars';
  setDefaultCurrency(block.dataset.currency || null);

  let blockProps = {};
  try {
    if (block.dataset.model) blockProps = JSON.parse(block.dataset.model);
  } catch (err) {
    console.error('Invalid block model JSON', err);
  }
  if (blockProps.currency == null) blockProps.currency = block.dataset.currency || null;

  block.replaceChildren();
  try {
    renderStars(block, blockProps);
  } catch (err) {
    console.error('Render error', err);
  }
}
