/**
 * EDS Block: product-card
 * Generated by AEM Migration Agent
 * Behavior IR: product-card
 * Framework: react
 */

import { readBlockConfig } from '../../scripts/aem.js';
import {
  setDefaultCurrency,
  renderProductCard,
} from '../shared/generated-jsx.js';
/* eslint-disable no-console */

export default async function decorate(block) {
  if (block.dataset.blockName == null) block.dataset.blockName = 'product-card';
  // Read authored model fields before replacing the UE-delivered table DOM.
  // UE renders each model field as its own single-column row in model order,
  // while document authoring uses two-column key/value rows parsed by
  // readBlockConfig. Support both. Do NOT call moveInstrumentation(block)
  // with a single arg here - it strips the block's data-aue-* attributes.
  if (block.dataset.currency == null) block.dataset.currency = '₹';
  setDefaultCurrency(block.dataset.currency || null);

  const fieldNames = ['title', 'price', 'category', 'stock'];
  const flat = { ...readBlockConfig(block) };
  [...block.querySelectorAll(':scope > div')].forEach((row, index) => {
    const name = fieldNames[index];
    if (row.children.length === 1 && name && flat[name] == null) {
      const value = ((row.children[0].textContent || '').trim());
      if (value) flat[name] = value;
    }
  });
  // Group flat authored fields (from the UE model) back under the render's object props.
  const blockProps = { ...flat };
  Object.entries({ product: ['title', 'price', 'category', 'stock'] }).forEach(([key, fields]) => {
    if (blockProps[key] == null && fields.some((f) => blockProps[f] != null)) {
      const grouped = {};
      fields.forEach((f) => {
        if (blockProps[f] != null) grouped[f] = blockProps[f];
      });
      blockProps[key] = grouped;
    }
  });
  if (blockProps.currency == null) blockProps.currency = block.dataset.currency || null;

  block.replaceChildren();
  try {
    renderProductCard(block, blockProps);
  } catch (err) {
    console.error('Render error', err);
  }
}
