/**
 * EDS Block: Header
 * Generated by AEM Migration Agent
 * Behavior IR: Header
 * Framework: vue
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  formatPrice,
  applyInlineStyle,
  appendText,
  dispatchEvent,
  setDefaultCurrency,
  renderHeader,
} from '../shared-new/generated-jsx.js';

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'Header';
  setDefaultCurrency(block.dataset.currency || null);

  let blockProps = {};
  try {
    if (block.dataset.model) blockProps = JSON.parse(block.dataset.model);
  } catch (err) {
    console.error('Invalid block model JSON', err);
  }
  if (blockProps.currency == null) blockProps.currency = block.dataset.currency || null;

  block.replaceChildren();
  try {
    renderHeader(block, blockProps);
  } catch (err) {
    console.error('Render error', err);
  }
}
