/**
 * EDS Block: badges
 * Generated by AEM Migration Agent
 * Behavior IR: badges
 * Framework: react
 */

import { readBlockConfig } from '../../scripts/aem.js';
import {
  setDefaultCurrency,
  renderBadges,
} from '../shared/generated-jsx.js';
/* eslint-disable no-console */

export default async function decorate(block) {
  if (block.dataset.blockName == null) block.dataset.blockName = 'badges';
  // Read authored model fields before replacing the UE-delivered table DOM.
  // UE renders each model field as its own single-column row in model order,
  // while document authoring uses two-column key/value rows parsed by
  // readBlockConfig. Support both. Do NOT call moveInstrumentation(block)
  // with a single arg here - it strips the block's data-aue-* attributes.
  if (block.dataset.currency == null) block.dataset.currency = '₹';
  setDefaultCurrency(block.dataset.currency || null);

  const fieldNames = ['children', 'variant'];
  const flat = { ...readBlockConfig(block) };
  [...block.querySelectorAll(':scope > div')].forEach((row, index) => {
    const name = fieldNames[index];
    if (row.children.length === 1 && name && flat[name] == null) {
      const value = (row.children[0].textContent || '').trim();
      if (value) flat[name] = value;
    }
  });
  const blockProps = { ...flat };
  if (blockProps.currency == null) blockProps.currency = block.dataset.currency || null;

  block.replaceChildren();
  try {
    renderBadges(block, blockProps);
  } catch (err) {
    console.error('Render error', err);
  }
}
