/**
 * EDS Block: Badges
 * Generated by AEM Migration Agent
 * Behavior IR: Badges
 * Framework: react
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  setDefaultCurrency,
  renderBadges,
} from '../shared/generated-jsx.js';

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'Badges';
  if (block.dataset.currency == null) block.dataset.currency = '₹';
  setDefaultCurrency(block.dataset.currency || null);

  let blockProps = {};
  try {
    if (block.dataset.model) blockProps = JSON.parse(block.dataset.model);
  } catch (err) {
    console.error('Invalid block model JSON', err); // eslint-disable-line no-console
  }
  if (blockProps.currency == null) blockProps.currency = block.dataset.currency || null;

  block.replaceChildren();
  try {
    renderBadges(block, blockProps);
  } catch (err) {
    console.error('Render error', err); // eslint-disable-line no-console
  }
}
