/**
 * EDS Block: product-list
 * Generated by AEM Migration Agent
 * Behavior IR: product-list
 * Framework: angular
 */

import {
  setDefaultCurrency,
  renderProduct_list,
} from '../shared/generated-jsx.js';
/* eslint-disable no-console */

const componentEventListeners = new WeakMap();


export default async function decorate(block) {
  if (block.dataset.blockName == null) block.dataset.blockName = 'product-list';
  setDefaultCurrency(block.dataset.currency || null);

  const entityKey = block.dataset.entityKey || 'id';
  // Local mock API fallback so the block renders even before the data-source
  // property is authored in UE. Set Data Source URL in UE for production.
  const apiBase = () => (block.dataset.dataSource || 'http://localhost:3005/products').replace(/\/+$/, '');
  let data = null;
  let loading = true;
  let error = null;
  let retry = () => {};
  let editingId = null;
  let editForm = {};
  let createForm = {};

  const renderBlock = (focusTarget = null) => {
    const selector = 'input, select, textarea, button, a[href], [tabindex]';
    const focusables = [...block.querySelectorAll(selector)];
    const focusIndex = focusTarget && block.contains(focusTarget) ? focusables.indexOf(focusTarget) : -1;
    const selectionStart = focusIndex >= 0 && 'selectionStart' in focusTarget ? focusTarget.selectionStart : null;
    const selectionEnd = focusIndex >= 0 && 'selectionEnd' in focusTarget ? focusTarget.selectionEnd : null;
    block.replaceChildren();
    try {
      renderProduct_list(block, {
        data,
        loading,
        error,
        retry,
        currency: block.dataset.currency || null,
        form: createForm,
        editingId,
        editForm,
      });
    } catch (err) {
      const p = document.createElement('p');
      p.textContent = `Render error: ${err instanceof Error ? err.message : String(err)}`;
      block.appendChild(p);
      console.error(err);
    }
    if (focusIndex >= 0) {
      const nextFocus = block.querySelectorAll(selector)[focusIndex];
      nextFocus?.focus();
      if (selectionStart != null && typeof nextFocus?.setSelectionRange === 'function') {
        nextFocus.setSelectionRange(selectionStart, selectionEnd);
      }
    }
  };

  const load = async () => {
    loading = true;
    error = null;
    renderBlock();
    try {
      const endpoint = apiBase();
      const response = await fetch(endpoint);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      data = await response.json();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
      renderBlock();
    }
  };

  // Orchestrator state machine: consumes the component's dispatched events and
  // replays the source script handlers (real API mutations when the component
  // used an API service, otherwise local model updates).
  const onComponentEvent = async (ev) => {
    const source = ev.detail?.event?.target;
    if (source && !block.contains(source)) return;
    const { name, args = [] } = ev.detail || {};
    if (name === 'startEdit') {
      const entity = args[0];
      if (!entity) return;
      editingId = entity[entityKey];
      editForm = { ...entity };
      renderBlock();
    } else if (name === 'saveEdit' && Array.isArray(data)) {
      const id = args[0];
      try {
        const response = await fetch(`${apiBase()}/${id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...editForm, [entityKey]: id }),
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const updated = await response.json();
        data = data.map((u) => (u[entityKey] === id ? { ...u, ...updated } : u));
      } catch (err) {
        error = err instanceof Error ? err.message : String(err);
      }
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'cancelEdit') {
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'handleDelete' && Array.isArray(data)) {
      const id = args[0];
      try {
        const response = await fetch(`${apiBase()}/${id}`, {
          method: 'DELETE',
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        data = data.filter((u) => u[entityKey] !== id);
      } catch (err) {
        error = err instanceof Error ? err.message : String(err);
      }
      if (editingId === id) { editingId = null; editForm = {}; }
      renderBlock();
    } else if (name === 'updateField') {
      const [field, value] = args;
      if (editingId != null) editForm = { ...editForm, [field]: value || '' };
      else createForm = { ...createForm, [field]: value || '' };
      renderBlock(source);
    } else if (name === 'handleSubmit') {
      if (Object.keys(createForm).length === 0) return;
      try {
        const response = await fetch(apiBase(), {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(createForm),
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const created = await response.json();
        data = [created, ...(Array.isArray(data) ? data : [])];
      } catch (err) {
        error = err instanceof Error ? err.message : String(err);
      }
      createForm = {};
      renderBlock();
    }
  };
  const previousHandler = componentEventListeners.get(block);
  if (previousHandler) document.removeEventListener('eds:component-event', previousHandler);
  document.addEventListener('eds:component-event', onComponentEvent);
  componentEventListeners.set(block, onComponentEvent);

  retry = load;
  await load();
}
