/**
 * EDS Block: ProductCard
 * Generated by AEM Migration Agent
 * Behavior IR: ProductCard
 * Framework: react
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  formatPrice,
  applyInlineStyle,
  appendText,
  dispatchEvent,
  setDefaultCurrency,
  renderProductCard,
} from '../shared/generated-jsx.js';

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'ProductCard';
  if (block.dataset.currency == null) block.dataset.currency = '₹';
  setDefaultCurrency(block.dataset.currency || null);

  let blockProps = {};
  try {
    if (block.dataset.model) blockProps = JSON.parse(block.dataset.model);
  } catch (err) {
    console.error('Invalid block model JSON', err);
  }
  // Group flat authored fields (from the UE model) back under the render's object props.
  for (const [key, fields] of Object.entries({"product":["title","price","category","stock"]})) {
    if (blockProps[key] == null && fields.some((f) => blockProps[f] != null)) {
      const grouped = {};
      for (const f of fields) if (blockProps[f] != null) grouped[f] = blockProps[f];
      blockProps[key] = grouped;
    }
  }
  if (blockProps.currency == null) blockProps.currency = block.dataset.currency || null;

  block.replaceChildren();
  try {
    renderProductCard(block, blockProps);
  } catch (err) {
    console.error('Render error', err);
  }
}
