/**
 * EDS Block: App
 * Generated by AEM Migration Agent
 * Behavior IR: App
 * Framework: vue
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  formatPrice,
  applyInlineStyle,
  appendText,
  dispatchEvent,
  setDefaultCurrency,
  renderApp,
} from '../shared-new/generated-jsx.js';

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'App';
  setDefaultCurrency(block.dataset.currency || null);

  let data = null;
  let loading = true;
  let error = null;
  let retry = () => {};

  const renderBlock = () => {
    block.replaceChildren();
    try {
      renderApp(block, { data, loading, error, retry, currency: block.dataset.currency || null });
    } catch (err) {
      const p = document.createElement('p');
      p.textContent = 'Render error: ' + (err instanceof Error ? err.message : String(err));
      block.appendChild(p);
      console.error(err);
    }
  };

  const load = async () => {
    loading = true;
    error = null;
    renderBlock();
    try {
      const response = await fetch("https://fakestoreapi.com/users");
      if (!response.ok) throw new Error('HTTP ' + response.status);
      data = await response.json();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
      renderBlock();
    }
  };

  retry = load;
  await load();
}
