/**
 * EDS Block: App
 * Generated by AEM Migration Agent
 * Behavior IR: App
 * Framework: vue
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  setDefaultCurrency,
  renderApp,
} from '../shared-new/generated-jsx.js';

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'App';
  setDefaultCurrency(block.dataset.currency || null);

  let data = null;
  let loading = true;
  let error = null;
  let retry = () => {};
  let editingId = null;
  let editForm = {};
  let createForm = { username: '', email: '', password: '' };

  const renderBlock = () => {
    block.replaceChildren();
    try {
      renderApp(block, {
        data,
        loading,
        error,
        retry,
        currency: block.dataset.currency || null,
        editingId,
        editForm,
        createForm,
      });
    } catch (err) {
      const p = document.createElement('p');
      p.textContent = `Render error: ${err instanceof Error ? err.message : String(err)}`;
      block.appendChild(p);
      // eslint-disable-next-line no-console
      console.error(err);
    }
  };

  const load = async () => {
    loading = true;
    error = null;
    renderBlock();
    try {
      const response = await fetch('https://dummyjson.com/users');
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      data = (await response.json()).users;
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
      renderBlock();
    }
  };

  document.addEventListener('eds:component-event', (ev) => {
    const { name, args = [] } = ev.detail || {};
    if (name === 'startEdit') {
      const user = args[0];
      if (user) {
        editingId = user.id;
        editForm = { username: user.username, email: user.email, password: user.password };
        renderBlock();
      }
    } else if (name === 'saveEdit' && Array.isArray(data)) {
      data = data.map((u) => (u.id === args[0] ? { ...u, ...editForm } : u));
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'cancelEdit') {
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'handleDelete' && Array.isArray(data)) {
      data = data.filter((u) => u.id !== args[0]);
      if (editingId === args[0]) {
        editingId = null;
        editForm = {};
      }
      renderBlock();
    } else if (name === 'updateField' && editingId != null) {
      const [field, value] = args;
      editForm = { ...editForm, [field]: value || '' };
    } else if (name === 'updateField') {
      const [field, value] = args;
      createForm = { ...createForm, [field]: value || '' };
    } else if (name === 'handleSubmit' && createForm.username && createForm.email && createForm.password) {
      data = [{ id: Date.now(), ...createForm }, ...(Array.isArray(data) ? data : [])];
      createForm = { username: '', email: '', password: '' };
      renderBlock();
    }
  });

  retry = load;
  await load();
}
