/**
 * EDS Block: App
 * Generated by AEM Migration Agent
 * Behavior IR: App
 * Framework: vue
 */

import { moveInstrumentation } from '../../scripts/scripts.js';
import {
  setDefaultCurrency,
  renderApp,
} from '../shared-new/generated-jsx.js';
/* eslint-disable no-console */

export default async function decorate(block) {
  moveInstrumentation(block);
  if (block.dataset.blockName == null) block.dataset.blockName = 'App';
  setDefaultCurrency(block.dataset.currency || null);

  let data = null;
  let loading = true;
  let error = null;
  let retry = () => {};
  let editingId = null;
  let editForm = {};
  let createForm = {};

  const renderBlock = () => {
    block.replaceChildren();
    try {
      renderApp(block, {
        data,
        loading,
        error,
        retry,
        currency: block.dataset.currency || null,
        form: createForm,
        editingId,
        editForm,
      });
    } catch (err) {
      const p = document.createElement('p');
      p.textContent = `Render error: ${err instanceof Error ? err.message : String(err)}`;
      block.appendChild(p);
      console.error(err);
    }
  };

  const load = async () => {
    loading = true;
    error = null;
    renderBlock();
    try {
      const response = await fetch('https://fakestoreapi.com/users');
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      data = await response.json();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
      renderBlock();
    }
  };

  // Orchestrator state machine: consumes the component's dispatched events and
  // drives the local data model so create/update/delete/edit behave like the
  // original component's script handlers.
  const onComponentEvent = (ev) => {
    if (!ev.target || !block.contains(ev.target)) return;
    const { name, args = [] } = ev.detail || {};
    if (name === 'startEdit') {
      const user = args[0];
      if (!user) return;
      editingId = user.id;
      editForm = { username: user.username ?? '', email: user.email ?? '', password: user.password ?? '' };
      renderBlock();
    } else if (name === 'saveEdit' && Array.isArray(data)) {
      const id = args[0];
      data = data.map((u) => (u.id === id ? { ...u, ...editForm } : u));
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'cancelEdit') {
      editingId = null;
      editForm = {};
      renderBlock();
    } else if (name === 'handleDelete' && Array.isArray(data)) {
      const id = args[0];
      data = data.filter((u) => u.id !== id);
      if (editingId === id) { editingId = null; editForm = {}; }
      renderBlock();
    } else if (name === 'updateField') {
      const [field, value] = args;
      if (editingId != null) editForm = { ...editForm, [field]: value || '' };
      else createForm = { ...createForm, [field]: value || '' };
    } else if (name === 'handleSubmit') {
      const { username = '', email = '', password = '' } = createForm;
      if (!username || !email || !password) return;
      data = [{ id: Date.now(), ...createForm }, ...(Array.isArray(data) ? data : [])];
      createForm = {};
      renderBlock();
    }
  };
  document.addEventListener('eds:component-event', onComponentEvent);

  retry = load;
  await load();
}
